FROM jenkins/jenkins:lts

USER root

# Instalar Maven, Docker y Docker Compose (Plugin V2)
RUN apt-get update && apt-get install -y \
    maven \
    docker.io \
    docker-compose-v2 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar plugins para que el dashboard ya esté configurado
RUN jenkins-plugin-cli --plugins "maven-plugin docker-workflow docker-plugin git"

# Desactivar el asistente de configuración
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

USER root