version: '3.8'

services:
  database:
    image: postgres:18
    container_name: skillswap_db_container
    environment:
      POSTGRES_DB: skillswap_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

volumes:
  postgres_data: